name: test & lint

on:
  pull_request:
    branches: [develop]

jobs:
  tests-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      - name: Run tests & lint
        run: |
          yarn install --frozen-lockfile
          yarn test
          yarn lint